# Generated by Django 5.2.3 on 2025-07-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='offer',
        ),
    ]
